// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Identity
{
    [Table("Allowance_deduction")]
    public partial class Allowance_deduction
    {
        [Key]
        public int AllowanceID { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string DefaultDesc { get; set; }
        public int? TypeID { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? Amount { get; set; }
        public int? CalculateTypeID { get; set; }
        public int? NatureID { get; set; }
        public int? IsDefault { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        [Key]
        public int ProjectID { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string DefaultDescEn { get; set; }
        public int? CalculateWithOvertime { get; set; }
        public int? CalculateWithAttendanceDeduction { get; set; }
    }
}