// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using DataAccessLayer.Contracts;

namespace DataAccessLayer.Models
{
    public partial class LookupTable: IMustHaveProject
    {
        
    }
}