// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Keyless]
    [Table("AttendnaceLog")]
    public partial class AttendnaceLog
    {
        public int ID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AttDate { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Type { get; set; }
        public int? EmployeeID { get; set; }
        public int? StatusID { get; set; }
        public int? attdateint { get; set; }
        public int ProjectID { get; set; }
        public int? DateOnly { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string IP { get; set; }
        public int? Dateasint { get; set; }
    }
}