// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("AttendancePath")]
    public partial class AttendancePath
    {
        [Key]
        public int ID { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string path { get; set; }
        [Key]
        public int ProjectID { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("AttendancePaths")]
        public virtual Project Project { get; set; }
    }
}