// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("AttendancePathSetup")]
    public partial class AttendancePathSetup
    {
        [Key]
        public int ID { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string IP { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Port { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string UserName { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Password { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string WindowsVersion { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string TypeDesc { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string MaxLogID { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string MaxLogDate { get; set; }
        [Key]
        public int ProjectID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string MachineNumber { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string MachineName { get; set; }
        public int? timezone { get; set; }
        public int? Currenttimezone { get; set; }
        public int? DeviceModel { get; set; }
        public int? CreatedBy { get; set; }
        public int? CreationDate { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("AttendancePathSetups")]
        public virtual Project Project { get; set; }
    }
}