// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Keyless]
    [Table("BAK_EMployeesSerElDawaa")]
    public partial class BAK_EMployeesSerElDawaa
    {
        [StringLength(200)]
        [Unicode(false)]
        public string SerialNo { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string EmpName { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string EmpNameEn { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string EmpNo { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Additional { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string taxType { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string SSNType { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Department { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Section { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string JobTitle { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string SectionManager { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string BankName { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Iban { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string BirthDate { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string PhoneNo { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Address { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string PersonEmergency1 { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string PhoneEmergency1 { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string PersonEmergency2 { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string PhoneEmergency2 { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string DateOfStartDateinMinistry { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Gender { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Nationality { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string UserName { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string userPAssword { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string NationalNo { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string SSNNo { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string BalanceVacation { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string SSNSalary { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string BdalEdarah { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string takmelahElrateb { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string BadalKhebra { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string BadalTa3am { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string BadalMwasalty { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string badalRotaion { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string BadalMonawabeh { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string BadalJame3 { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Edafi3adi { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string BadalSheft { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string EdafiEl3eed { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Mardodkhasmeyat { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Mokafaah { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string BadalRokhsah { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Badal3moleh { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Total { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string DateOfParticipate { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string DateofparticipateSSN { get; set; }
    }
}