// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Keyless]
    public partial class Button
    {
        [StringLength(50)]
        [Unicode(false)]
        public string ButtonID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ButtonCode { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string parentButtonCode { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ParentScreenID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string GridName { get; set; }
    }
}