// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Keyless]
    [Table("CheckInOutTemp")]
    public partial class CheckInOutTemp
    {
        public int ID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string BadgeNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CheckTime { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CheckType { get; set; }
        public int? Flag { get; set; }
        public int ProjectID { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string IP { get; set; }
    }
}