// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    public partial class Day
    {
        [Key]
        public int DayID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string DayDesc { get; set; }
        public int? StatusID { get; set; }
        [Key]
        public int ProjectID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string DayDescAr { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("Days")]
        public virtual Project Project { get; set; }
    }
}