// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("EmployeeAttendance")]
    [Index("CheckIn", "ProjectID", "AttendanceDate", Name = "IX_EmployeeAttendance_111")]
    [Index("ProjectID", "AttendanceDate", Name = "IX_EmployeeAttendance_1111")]
    [Index("ProjectID", Name = "NonClusteredIndex-20220712-031430")]
    [Index("ProjectID", "AttendanceDate", Name = "ix_EmplAtt11")]
    [Index("AttendanceDate", Name = "ix_EmployeeAttendance_1")]
    [Index("EmployeeID", Name = "ix_EmployeeAttendance_2")]
    public partial class EmployeeAttendance
    {
        [Key]
        public int EmployeeID { get; set; }
        [Key]
        public int AttendanceDate { get; set; }
        public int? CheckIn { get; set; }
        public int? CheckOut { get; set; }
        public int? WeekDayID { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int? SettingID { get; set; }
        public int? BreakIn { get; set; }
        public int? BreakOut { get; set; }
        [Key]
        public int ProjectID { get; set; }
        public int? TempCheckIn { get; set; }
        public int? TempCheckOut { get; set; }
        public int? TempCheckinStatusID { get; set; }
        public int? TempCheckoutStatusID { get; set; }
        public int? ISAddedManual { get; set; }

        [ForeignKey("EmployeeID")]
        [InverseProperty("EmployeeAttendances")]
        public virtual Employee Employee { get; set; }
        [ForeignKey("ProjectID")]
        [InverseProperty("EmployeeAttendances")]
        public virtual Project Project { get; set; }
    }
}