// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("EmployeeOverTime")]
    [Index("AttendanceDate", Name = "ix_EmployeeOvertime_111")]
    public partial class EmployeeOverTime
    {
        [Key]
        public int EmployeeID { get; set; }
        [Key]
        public int AttendanceDate { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int? TotalHours { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string Notes { get; set; }

        [ForeignKey("EmployeeID")]
        [InverseProperty("EmployeeOverTimes")]
        public virtual Employee Employee { get; set; }
    }
}