// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("EmployeeLeavesLog")]
    [Index("EmployeeID", Name = "IX_EmployeeLeavesLog")]
    [Index("ProjectID", Name = "IX_EmployeeLeavesLog1")]
    public partial class EmployeeLeavesLog
    {
        [Key]
        public int EmployeeLeaveID { get; set; }
        public int EmployeeID { get; set; }
        public int? LeaveTypeID { get; set; }
        public int? LeaveDate { get; set; }
        public int? FromTime { get; set; }
        public int? ToTime { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int? BySystem { get; set; }
        public int ProjectID { get; set; }
        public int? statusid { get; set; }
        public int? approvalstatusid { get; set; }

        [ForeignKey("EmployeeID")]
        [InverseProperty("EmployeeLeavesLogs")]
        public virtual Employee Employee { get; set; }
        [ForeignKey("ProjectID")]
        [InverseProperty("EmployeeLeavesLogs")]
        public virtual Project Project { get; set; }
    }
}