// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Keyless]
    [Table("EmployeeShifts2022")]
    public partial class EmployeeShifts2022
    {
        public int EmployeeShiftID { get; set; }
        public int EmployeeID { get; set; }
        public int? ShiftID { get; set; }
        public int? FromDate { get; set; }
        public int? ToDate { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int ProjectID { get; set; }
    }
}