// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Index("EmployeeID", Name = "ix_EmployeeShifts_2")]
    [Index("ShiftID", Name = "ix_EmployeeShifts_3")]
    [Index("FromDate", Name = "ix_EmployeeShifts_4")]
    [Index("FromDate", "ToDate", Name = "ix_EmployeeShifts_5")]
    public partial class EmployeeShift
    {
        [Key]
        public int EmployeeShiftID { get; set; }
        [Key]
        public int EmployeeID { get; set; }
        public int? ShiftID { get; set; }
        public int? FromDate { get; set; }
        public int? ToDate { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        [Key]
        public int ProjectID { get; set; }

        [ForeignKey("EmployeeID")]
        [InverseProperty("EmployeeShifts")]
        public virtual Employee Employee { get; set; }
        [ForeignKey("ProjectID")]
        [InverseProperty("EmployeeShifts")]
        public virtual Project Project { get; set; }
    }
}