// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("EMployeeWeeklyHoliday")]
    [Index("YearID", "MonthID", "DayID", Name = "IX_EWH")]
    [Index("EmployeeID", "YearID", "MonthID", Name = "ix_EMployeeWeeklyHoliday")]
    public partial class EMployeeWeeklyHoliday
    {
        [Key]
        public int EmployeeID { get; set; }
        [Key]
        public int MonthID { get; set; }
        [Key]
        public int YearID { get; set; }
        [Key]
        public int DayID { get; set; }
        public int? StatusID { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }

        [ForeignKey("EmployeeID")]
        [InverseProperty("EMployeeWeeklyHolidays")]
        public virtual Employee Employee { get; set; }
    }
}