// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Keyless]
    [Table("EmployeeSalary")]
    public partial class EmployeeSalary
    {
        public int? EmployeeID { get; set; }
        public int? CurrentYearID { get; set; }
        public int? CurrentMonthID { get; set; }
        public int? TypeID { get; set; }
        public int? SubTypeID { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? Amount { get; set; }
        public int? FromDate { get; set; }
        public int? ToDate { get; set; }
        public int? StatusID { get; set; }
        public int? CalculationDate { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? AdditionalInWork { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? AdditionalInHoliday { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? morninglate { get; set; }
        public int? workingdays { get; set; }
        public int? monthdays { get; set; }
        public int? missingcheckin { get; set; }
        public int? missingcheckout { get; set; }
        public int? ProjectID { get; set; }
        public int? BreakLate { get; set; }
        public int? CountLate { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? CompanyShare { get; set; }
        public int? EarlyLeaves { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? AdditionalInWorkAmount { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? AdditionalInHolidayAmount { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? HourAmountInwork { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? HourAmountInHoliday { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? HourAmountInworkAdditional { get; set; }
        public int? OverTime1 { get; set; }
        public int? OverTime2 { get; set; }
        public int? OverTime3 { get; set; }
        public int? OverTime4 { get; set; }
        public int? OverTime5 { get; set; }
        public int? OnlyLeaves { get; set; }
        public int? remainingBalanceInMinute { get; set; }
        public int? MissingCheckin1 { get; set; }
        public int? MissingCheckin2 { get; set; }
        public int? DailyWorkInMinutes { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? MorningLateAmount { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? OnlyLeavesAmount { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? AdditionalDuringHoliday { get; set; }
        public int? AdditionalDuringHolidayInMinute { get; set; }
        public int? remainingBalanceInDays { get; set; }
        public int? TotalCheckinDays { get; set; }

        [ForeignKey("EmployeeID")]
        public virtual Employee Employee { get; set; }
        [ForeignKey("ProjectID")]
        public virtual Project Project { get; set; }
    }
}