// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    public partial class EmployeeShiftDetail
    {
        [Key]
        public int EmployeeID { get; set; }
        [Key]
        public int ShiftID { get; set; }
        [Key]
        public int DayID { get; set; }
        [Key]
        public int ShiftDate { get; set; }

        [ForeignKey("EmployeeID")]
        [InverseProperty("EmployeeShiftDetails")]
        public virtual Employee Employee { get; set; }
        [ForeignKey("ShiftID")]
        [InverseProperty("EmployeeShiftDetails")]
        public virtual Shift Shift { get; set; }
    }
}