// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("EmployeeAttendance2")]
    public partial class EmployeeAttendance2
    {
        [Key]
        public int ID { get; set; }
        public int? EmployeeID { get; set; }
        public int? AttendanceDate { get; set; }
        public int? CheckIn { get; set; }
        public int? Checkout { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }

        [ForeignKey("EmployeeID")]
        [InverseProperty("EmployeeAttendance2s")]
        public virtual Employee Employee { get; set; }
    }
}