// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("EmployeeEducation")]
    public partial class EmployeeEducation
    {
        [Key]
        public int EmployeeID { get; set; }
        [Key]
        public int DetailID { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Institution { get; set; }
        public int? DegreeID { get; set; }
        [MaxLength(100)]
        public byte[] Attachment { get; set; }
        public int? Major { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CompletionMonth { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CompletionYear { get; set; }
        public int? CountryID { get; set; }
        public int? CityID { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? Grade { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? GradeTotal { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Description { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        [Key]
        public int ProjectID { get; set; }

        [ForeignKey("EmployeeID")]
        [InverseProperty("EmployeeEducations")]
        public virtual Employee Employee { get; set; }
        [ForeignKey("ProjectID")]
        [InverseProperty("EmployeeEducations")]
        public virtual Project Project { get; set; }
    }
}