// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("EmployeePaper")]
    public partial class EmployeePaper
    {
        [Key]
        public int EmployeeID { get; set; }
        public int PaperID { get; set; }
        [Key]
        public int DetailID { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string PaperPath { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string Notes { get; set; }
        public int? CratedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }

        [ForeignKey("EmployeeID")]
        [InverseProperty("EmployeePapers")]
        public virtual Employee Employee { get; set; }
    }
}