// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("EmployeeHRService")]
    public partial class EmployeeHRService
    {
        [Key]
        public int EmployeeHRServiceID { get; set; }
        [Key]
        public int EmployeeID { get; set; }
        public int? HRServiceID { get; set; }
        public int? HRServiceDate { get; set; }
        [StringLength(4000)]
        [Unicode(false)]
        public string ReasonDesc { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int? StatusID { get; set; }
        public int? MonthID { get; set; }
        public int? YearID { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string ServiceText { get; set; }
        public int? BankID { get; set; }
        public int? BranchID { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string AttachmentDesc { get; set; }
    }
}