// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("EmployeeHoliday")]
    public partial class EmployeeHoliday
    {
        [Key]
        public int EmployeeID { get; set; }
        public int? DayID { get; set; }
        [Key]
        public int MonthID { get; set; }
        [Key]
        public int YearID { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }

        [ForeignKey("EmployeeID")]
        [InverseProperty("EmployeeHolidays")]
        public virtual Employee Employee { get; set; }
    }
}