// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Keyless]
    [Table("GeneratedUSerName")]
    public partial class GeneratedUSerName
    {
        [StringLength(1000)]
        [Unicode(false)]
        public string PasswordID { get; set; }
        public int? AutoNumber { get; set; }
    }
}