// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetAllowance_deductionResult
    {
        public int AllowanceID { get; set; }
        public string DefaultDesc { get; set; }
        public int? TypeID { get; set; }
        public decimal? Amount { get; set; }
        public int? CalculateTypeID { get; set; }
        public int? NatureID { get; set; }
        public int? IsDefault { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public int ProjectID { get; set; }
        public int EnableDelete { get; set; }
        public int? CalculateWithOvertime { get; set; }
        public int? CalculateWithAttendanceDeduction { get; set; }
    }
}
