// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetAutomaticAttendanceActioonsResult
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int? EmployeeNumber { get; set; }
        public DateTime? AttDate { get; set; }
        public string Type { get; set; }
        public int? ID { get; set; }
        public int? CurrentSTatusID { get; set; }
        public string IsSolved { get; set; }
        public int? OldCheckIn { get; set; }
        public int? OldCheckOut { get; set; }
        public int? OldBreakIn { get; set; }
        public int? OldBreakOut { get; set; }
        public string ActionTypeDesc { get; set; }
        public int CheckIn { get; set; }
        public int CheckOut { get; set; }
        public int? StartTime { get; set; }
        public int? EndTime { get; set; }
        public int? notes { get; set; }
        public int? IsWorkingDay { get; set; }
        public int BreakIn { get; set; }
        public int BreakOut { get; set; }
    }
}
