// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetAutomaticLeaveDuringDayTableResult
    {
        public int? id { get; set; }
        public int? DateOnly { get; set; }
        public int? minTime { get; set; }
        public int? maxtime { get; set; }
    }
}
