// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetAttendancePathSetupResult
    {
        public int ID { get; set; }
        public string IP { get; set; }
        public string Port { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string WindowsVersion { get; set; }
        public string TypeDesc { get; set; }
        public int? MaxLogID { get; set; }
        public string MaxLogDate { get; set; }
        public string StatusDesc { get; set; }
        public string MachineNumber { get; set; }
        public int colStatus { get; set; }
        public string MachineName { get; set; }
        public int DeviceModel { get; set; }
    }
}
