// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetAttendancePathResult
    {
        public int ID { get; set; }
        public string path { get; set; }
        public int ProjectID { get; set; }
    }
}
