// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetAttendanceResult
    {
        public int ID { get; set; }
        public string AttDate { get; set; }
        public string Type { get; set; }
        public int? EmployeeID { get; set; }
        public int? StatusID { get; set; }
        public int? attdateint { get; set; }
        public int ProjectID { get; set; }
    }
}
