// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeLoanReportTotalsResult
    {
        public int EmployeeID { get; set; }
        public string LoanDate { get; set; }
        public string EmployeeName { get; set; }
        public int? EmployeeNumber { get; set; }
        public int Salary { get; set; }
        public decimal? CurrentValue { get; set; }
        public decimal? ScheduledValue { get; set; }
        public string companyname { get; set; }
        public string footertitle1 { get; set; }
        public string footertitle2 { get; set; }
        public string v_FromDate { get; set; }
        public string v_ToDate { get; set; }
        public string imagepath { get; set; }
    }
}
