// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeAttendanceDailyAbsentResult
    {
        public int? EmployeeID { get; set; }
        public int? AttendanceDate { get; set; }
        public string checkIn { get; set; }
        public string Checkout { get; set; }
        public string EmployeeName { get; set; }
        public int? EmployeeNumber { get; set; }
        public int EnableDelete { get; set; }
        public int EnableUpdate { get; set; }
        public string CurrDate { get; set; }
        public string Notes { get; set; }
        public string companyname { get; set; }
        public string footertitle1 { get; set; }
        public string footertitle2 { get; set; }
        public string imagepath { get; set; }
        public string noofhours { get; set; }
        public string allhours { get; set; }
    }
}
