// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeShiftCheckResult
    {
        public int EmployeeID { get; set; }
        public int ShiftID { get; set; }
        public string ShiftName { get; set; }
        public int IsChecked { get; set; }
    }
}
