// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeLoanResult
    {
        public int EmployeeLoanID { get; set; }
        public int EmployeeID { get; set; }
        public int? LoanDate { get; set; }
        public decimal? LoanAmount { get; set; }
        public string Notes { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public int ProjectID { get; set; }
        public string EmployeeName { get; set; }
        public int? EmployeeNumber { get; set; }
        public int EnableDelete { get; set; }
        public string StartDate { get; set; }
        public string JobTitleName { get; set; }
        public int Salary { get; set; }
        public string LoanTypeDesc { get; set; }
        public int? LoanTypeID { get; set; }
        public decimal? CurrentValue { get; set; }
        public decimal? ScheduledValue { get; set; }
    }
}
