// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeAttendanceByHoursResult
    {
        public int EmployeeID { get; set; }
        public int? AttendanceDate { get; set; }
        public int? ShiftID1 { get; set; }
        public int? ShiftID2 { get; set; }
        public int? ShiftID3 { get; set; }
        public string WorkingHours1 { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? Creationdate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public int IsWorkingDay { get; set; }
        public int? EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public string TempShiftName1 { get; set; }
        public string TempShiftName2 { get; set; }
        public string TempShiftName3 { get; set; }
        public string DayDesc { get; set; }
        public string WorkingHours2 { get; set; }
        public string WorkingHours3 { get; set; }
    }
}
