// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeAttendanceResult
    {
        public int? EmployeeID { get; set; }
        public int? AttendanceDate { get; set; }
        public int CheckIn { get; set; }
        public int CheckOut { get; set; }
        public int? WeekDayID { get; set; }
        public int BreakIn { get; set; }
        public int BreakOut { get; set; }
        public int? ProjectID { get; set; }
        public int? EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public int? ShiftID { get; set; }
        public string ShiftName { get; set; }
        public int? StartTime { get; set; }
        public int? EndTime { get; set; }
        public string Notes { get; set; }
        public int? Checkoutaftermidnight { get; set; }
        public int? IsWorkingDay { get; set; }
        public int? IsVacation { get; set; }
        public int AllowedLate { get; set; }
        public int EarlyLeave { get; set; }
        public int CalculateAdditionalIfExceed { get; set; }
        public int MorningAttendanceasAdditional { get; set; }
        public int AllowedAdditionalBefore { get; set; }
        public int FixedDayID { get; set; }
        public int AllowedLatetooverride { get; set; }
        public int BreakStartTime { get; set; }
        public int BreakEndTime { get; set; }
        public int BreakPeriod { get; set; }
        public int BreakTypeID { get; set; }
        public string missingcheckin { get; set; }
        public string MissingChekout { get; set; }
        public string MorningLate10M { get; set; }
        public string MorningLate1Hour { get; set; }
        public string MorningLateGreaterThan1 { get; set; }
        public string EarlyLeave10M { get; set; }
        public string EarlyLeave1Hour { get; set; }
        public string EarlyLeaveGraterThan1 { get; set; }
        public string WithoutShift { get; set; }
        public string MissingCheckinWithCheckout { get; set; }
        public string Overtime { get; set; }
        public int? EmployeeVacationID { get; set; }
        public string DayDesc { get; set; }
        public int? ISAddedManual { get; set; }
        public string Systemtimeinminutes { get; set; }
        public string Approvedtimeinminutes { get; set; }
        public int? ApprovedStatusID { get; set; }
        public string EmployeeImage { get; set; }
		public string JobTitleName { get; set; }
        public int? AnyWhere { get; set; }
        public string workhoursinstring { get; set; }
    }
}
