// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeePaperResult
    {
        public int EmployeeID { get; set; }
        public int PaperID { get; set; }
        public int? DetailID { get; set; }
        public string PaperPath { get; set; }
        public string Notes { get; set; }
        public int? createdby { get; set; }
        public int? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public string EmployeeName { get; set; }
        public int? EmployeeNumber { get; set; }
        public string PaperDesc { get; set; }
        public int enabledelete { get; set; }
    }
}
