// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeePenaltyReportResult
    {
        public int EmployeePenaltyID { get; set; }
        public int? EmployeeID { get; set; }
        public int? PenaltyID { get; set; }
        public int? DayCount { get; set; }
        public string PunchmentDate { get; set; }
        public string ReasonDesc { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public string PunchmentTypeDesc { get; set; }
        public string EmployeeName { get; set; }
        public int? EmployeeNumber { get; set; }
        public int? StatusID { get; set; }
        public string StatusDesc { get; set; }
        public int EnableDelete { get; set; }
        public string companyname { get; set; }
        public string footertitle1 { get; set; }
        public string footertitle2 { get; set; }
        public string imagepath { get; set; }
        public string JobTitleName { get; set; }
        public string CareerNumber { get; set; }
        public string StartDate { get; set; }
        public string ColumnValue { get; set; }
        public int DeductDays { get; set; }
        public string DepartmentName { get; set; }
        public string EmployeeNameEn { get; set; }
    }
}
