// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeAttendanceTotalsResult
    {
        public int? EmployeeID { get; set; }
        public decimal? TotalHourByHours { get; set; }
        public decimal? IsFixedAttendnace { get; set; }
        public decimal? AdditionalInWork { get; set; }
        public decimal? AdditionalInHoliday { get; set; }
        public decimal? MissingCheckIn { get; set; }
        public decimal? MissingCheckOut { get; set; }
        public decimal? MinuteDiffMor { get; set; }
        public decimal? EarlyLeave { get; set; }
        public decimal? CountLate { get; set; }
        public decimal? CountEarlyLEave { get; set; }
        public decimal? BreakLate { get; set; }
        public decimal? ShouldCheckin { get; set; }
        public decimal? TotalHours { get; set; }
        public decimal? InjuryDeduction { get; set; }
        public decimal? MissingCheckoutValue { get; set; }
        public decimal? MissingCheckInValue { get; set; }
        public int? remainingBalance { get; set; }
        public int? remainingBalanceInMinute { get; set; }
        public int? ShiftDailyWorkInMinutes { get; set; }
        public int? ShiftNoOfDaysBerMonth { get; set; }
        public int? AdditionalInHolidayOnly { get; set; }
        public decimal? AdditionalInWork9 { get; set; }
        public decimal? AdditionalInHoliday9 { get; set; }
        public decimal? MinuteDiffMor9 { get; set; }
        public decimal? EarlyLeave9 { get; set; }
        public int? AdditionalInHolidayOnly9 { get; set; }
        public int? OnlyLeaves { get; set; }
        public decimal? OverTime1 { get; set; }
        public decimal? OverTime2 { get; set; }
        public decimal? OverTime3 { get; set; }
        public decimal? OverTime4 { get; set; }
        public decimal? OverTime5 { get; set; }
        public decimal? MissingCheckin1 { get; set; }
        public decimal? MissingCheckin2 { get; set; }
        public decimal? IsWithoutSalaryVacation { get; set; }
        public decimal? StaticOvertime { get; set; }
        public decimal? SalaryWhenWorkingByhours { get; set; }
        public int? TotalCheckinDays { get; set; }
    }
}
