// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeBalanceResult
    {
        public int EmployeeID { get; set; }
        public int YearID { get; set; }
        public int? CurrentBalance { get; set; }
        public int? PreviousBalance { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public int? ActualBalance { get; set; }
        public int ProjectID { get; set; }
    }
}
