// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeInjuryResult
    {
        public int EmployeeInjuryID { get; set; }
        public int EmployeeID { get; set; }
        public int? InjuryID { get; set; }
        public int? DayCount { get; set; }
        public int? InjuryDate { get; set; }
        public string ReasonDesc { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public string InjuryDesc { get; set; }
        public string EmployeeName { get; set; }
        public int? EmployeeNumber { get; set; }
        public int? StatusID { get; set; }
        public string StatusDesc { get; set; }
        public int EnableDelete { get; set; }
    }
}
