// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeNotificationsResult
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string StartDate { get; set; }
        public string ENDDATE { get; set; }
        public int? EmployeeNumber { get; set; }
    }
}
