// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeApprovalsResult
    {
        public int PrimaryKey { get; set; }
        public int EmployeeID { get; set; }
        public int? FromDate { get; set; }
        public int? ToDate { get; set; }
        public string Notes { get; set; }
        public int ProjectID { get; set; }
        public string EmployeeName { get; set; }
        public int? EmployeeNumber { get; set; }
        public string TypeDesc { get; set; }
        public string StatusDesc { get; set; }
        public int PageID { get; set; }
        public int? StatusID { get; set; }
        public int? ApprovalStatusID { get; set; }
        public string ApprovalProcessID { get; set; }
        public int? FromTime { get; set; }
        public int? ToTime { get; set; }
        public string PageTypeDesc { get; set; }
    }
}
