// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeEndContractReportResult
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int? EmployeeNumber { get; set; }
        public string NationalId { get; set; }
        public string SocialNumber { get; set; }
        public string CareerNumber { get; set; }
        public string JobTitleName { get; set; }
        public int? BirthDate { get; set; }
        public int? NationalityID { get; set; }
        public string MobileNo { get; set; }
        public string EmailNo { get; set; }
        public string EmergencyCallName { get; set; }
        public string EmergencyCallMobile { get; set; }
        public string AccountNo { get; set; }
        public string IBAN { get; set; }
        public string EmployeeImage { get; set; }
        public int ProjectID { get; set; }
        public string companyname { get; set; }
        public string footertitle1 { get; set; }
        public string footertitle2 { get; set; }
        public string imagepath { get; set; }
        public decimal? Salary { get; set; }
        public decimal? SocialSecuritySalary { get; set; }
        public string StatusDesc { get; set; }
        public string DepartmentName { get; set; }
        public string UserName { get; set; }
        public int? SSnType { get; set; }
        public string EmployeeAddress { get; set; }
        public string NationalityDesc { get; set; }
        public string ContractPeriod { get; set; }
        public string SalarySlipDesc { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    }
}
