// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeAllowancesResult
    {
        public int AllowanceID { get; set; }
        public string DefaultDesc { get; set; }
        public int EmployeeAllowanceID { get; set; }
        public int? EmployeeID { get; set; }
        public int StartDate { get; set; }
        public int EndDate { get; set; }
        public decimal? Amount { get; set; }
        public decimal? AllowanceAmount { get; set; }
        public int CalculateWithOvertime { get; set; }
        public string WithOverTimeDesc { get; set; }
        public int CalculatedWithOverTime { get; set; }
    }
}
