// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeAttendanceFNResult
    {
        public int? AttendanceDate { get; set; }
        public int? EmployeeID { get; set; }
        public int? CheckIn { get; set; }
        public int? CheckOut { get; set; }
        public int? WeekDayID { get; set; }
        public int? FromTime { get; set; }
        public int? ToTime { get; set; }
        public int? CalculateAdditionalIfExceed { get; set; }
        public int? IsWorkingDay { get; set; }
        public int? AllowedLate { get; set; }
        public int? AllowedLateInLeave { get; set; }
        public int? BreakOut { get; set; }
        public int? BreakIn { get; set; }
        public int? HasBreak { get; set; }
        public int? WithBreak { get; set; }
        public int? fromtime1 { get; set; }
        public int? LastTime { get; set; }
        public int? Overtime { get; set; }
        public int? FixedDayID { get; set; }
        public int? ShouldCheckin { get; set; }
        public int? TotalHours { get; set; }
        public int? LeaveCount { get; set; }
        public int? MorningAttendanceasAdditional { get; set; }
        public int? AllowedAdditionalBefore { get; set; }
        public int? IsInjuryVacation { get; set; }
        public int? IsDailyWork { get; set; }
        public int? DoubleHolidayinThursday { get; set; }
        public int? MissingCheckoutValue { get; set; }
        public int? ProjectID { get; set; }
        public int? ShiftID { get; set; }
        public string shiftname { get; set; }
        public int? Checkoutaftermidnight { get; set; }
        public int? FromBreak { get; set; }
        public int? ToBreak { get; set; }
        public int? BreakPeriod { get; set; }
        public int? BreakTypeID { get; set; }
        public string Notes { get; set; }
        public int? IsVacation { get; set; }
        public int? TempCheckoutStatusID { get; set; }
        public int? TempCheckinStatusID { get; set; }
        public int? TEmpCheckout { get; set; }
        public int? TempCheckin { get; set; }
        public int? DayID { get; set; }
        public int? IsActiveBreak { get; set; }
        public int? BreakDay { get; set; }
        public int? HolidayID { get; set; }
        public int? ShiftWorkingDay { get; set; }
        public int? NoofremainingDays { get; set; }
        public int? MaxOverTimePerDay { get; set; }
        public int? OnlyLeaves { get; set; }
        public int? EmployeeVacationID { get; set; }
        public string DayDesc { get; set; }
        public int? ISAddedManual { get; set; }
        public int? ShouldCheckout { get; set; }
        public int? IsWithoutSalaryVacation { get; set; }
        public decimal? WithoutSalaryVacationValue { get; set; }
        public decimal? StaticOverTime { get; set; }
        public int? ShiftHours1 { get; set; }
        public int? ShiftHours2 { get; set; }
        public int? ShiftHours3 { get; set; }
        public decimal? ShiftHourRate1 { get; set; }
        public decimal? ShiftHourRate2 { get; set; }
        public decimal? ShiftHourRate3 { get; set; }
        public int? EmployeeWeeklHolidayStatusID { get; set; }
        public int? ShouldCalExtraDays { get; set; }
    }
}
