// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeSalaryResult
    {
        public int? EmployeeID { get; set; }
        public int? CurrentYearID { get; set; }
        public int? CurrentMonthID { get; set; }
        public int? TypeID { get; set; }
        public int? SubTypeID { get; set; }
        public decimal? Amount { get; set; }
        public int? FromDate { get; set; }
        public int? ToDate { get; set; }
        public int? StatusID { get; set; }
        public int? CalculationDate { get; set; }
        public decimal? AdditionalInWork { get; set; }
        public decimal? AdditionalInHoliday { get; set; }
        public decimal? morninglate { get; set; }
        public int? workingdays { get; set; }
        public int? monthdays { get; set; }
        public int? missingcheckin { get; set; }
        public int? missingcheckout { get; set; }
        public int? ProjectID { get; set; }
        public int? EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public string StatusDesc { get; set; }
        public string SUBTYpeDesc { get; set; }
    }
}
