// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeHRServiceReportResult
    {
        public int EmployeeHRServiceID { get; set; }
        public int EmployeeID { get; set; }
        public int? HRServiceID { get; set; }
        public string HRServiceDate { get; set; }
        public string ReasonDesc { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public string HRServiceDesc { get; set; }
        public string EmployeeName { get; set; }
        public int? EmployeeNumber { get; set; }
        public int? StatusID { get; set; }
        public string StatusDesc { get; set; }
        public int EnableDelete { get; set; }
        public int? MonthID { get; set; }
        public int? YearID { get; set; }
        public int? BankID { get; set; }
        public int? BranchID { get; set; }
        public string ServiceText { get; set; }
        public string AttachmentDesc { get; set; }
        public string ServiceTypeID { get; set; }
        public string companyname { get; set; }
        public string footertitle1 { get; set; }
        public string footertitle2 { get; set; }
        public string imagepath { get; set; }
        public string NationalID { get; set; }
        public decimal Salary { get; set; }
        public string JobTitleNAme { get; set; }
        public string StartDate { get; set; }
    }
}
