// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetEmployeeSalaryReportResult
    {
        public int? EmployeeID { get; set; }
        public int? EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public int? StartDate2 { get; set; }
        public int? CalculationDate2 { get; set; }
        public decimal? NetSalary { get; set; }
        public decimal? Salary { get; set; }
        public decimal? TT { get; set; }
        public decimal SocialSecurityAmount { get; set; }
        public decimal AdditionalAmount { get; set; }
        public decimal LoanAmount { get; set; }
        public decimal TotalAllowances { get; set; }
        public decimal TotalDeduction { get; set; }
        public decimal OtherAllowances { get; set; }
        public decimal OtherDeductions { get; set; }
        public string StartDate { get; set; }
        public string CalculationDate { get; set; }
        public string AddInHoliday { get; set; }
        public string AddInWork { get; set; }
        public decimal AdditionalInHoliday2 { get; set; }
        public decimal AdditionalInWork2 { get; set; }
        public string NationalId { get; set; }
        public string JobTitleName { get; set; }
        public string companyname { get; set; }
        public string footertitle1 { get; set; }
        public string footertitle2 { get; set; }
        public string imagepath { get; set; }
        public string title { get; set; }
        public string MinuteDiffMor { get; set; }
        public int? monthdays { get; set; }
        public int? workingdays { get; set; }
        public int missingcheckin { get; set; }
        public int missingcheckout { get; set; }
        public decimal CompanyShare1 { get; set; }
        public int? CurrentYearID { get; set; }
        public int? CurrentMonthID { get; set; }
        public decimal? TotalsSalry1 { get; set; }
        public decimal LateAmount { get; set; }
        public decimal CheckOutAmount { get; set; }
        public decimal CheckInAmount { get; set; }
        public string LastDay { get; set; }
        public int? TypeID { get; set; }
        public decimal? AMount { get; set; }
        public string Desc_ { get; set; }
        public string SocialNumber { get; set; }
        public decimal? ActualSalary { get; set; }
        public string AllOvertime { get; set; }
        public string ALLLate { get; set; }
        public string Iban { get; set; }
        public decimal? AdditionalInHolidayAmount { get; set; }
        public decimal? AdditionalInWorkAmount { get; set; }
        public decimal? HourAmountInHoliday { get; set; }
        public decimal? HourAmountInwork { get; set; }
        public decimal? HourAmountInworkAdditional { get; set; }
        public string BankName { get; set; }
        public string DepartmentName { get; set; }
        public decimal Tax { get; set; }
        public decimal? remainingBalance { get; set; }
        public string BankGroup { get; set; }
        public string EmployeeNameAR { get; set; }
        public string EmployeeNameEn { get; set; }
        public string NationalityDesc { get; set; }
        public int? IncomeTaxType { get; set; }
        public int? IsAllEmployees { get; set; }
        public string PrintDate { get; set; }
        public string PrintTime { get; set; }
        public int? SerialNo { get; set; }
        public string Notes { get; set; }
        public string BankTransferNote { get; set; }
        public string NoteForSalary1 { get; set; }
        public string NoteForSalary2 { get; set; }
        public decimal BadlatAmount { get; set; }
        public decimal AwardAmount { get; set; }
        public int? IncomeTax1 { get; set; }
        public int? IncomeTax2 { get; set; }
        public int IncomeTax3 { get; set; }
        public decimal? BasicSalryForReport { get; set; }
        public decimal? OverTimeAmount { get; set; }
    }
}
