// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetHolidayResult
    {
        public int HolidayID { get; set; }
        public int? HolidayTypeID { get; set; }
        public int? FromDate { get; set; }
        public int? ToDate { get; set; }
        public string Notes { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public int ProjectID { get; set; }
        public string HolidayTypeDesc { get; set; }
        public int EnableDelete { get; set; }
    }
}
