// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetLeaveCountResult
    {
        public int? EmployeeID { get; set; }
        public int? TotalLeave { get; set; }
        public int? VacationCount { get; set; }
        public int? minusHrtransaction { get; set; }
        public int? PlusHRTransaction { get; set; }
        public int? EarlyandMorningLeaves { get; set; }
    }
}
