// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetLookupTableResult
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string ColumnValue { get; set; }
        public string ColumnDescription { get; set; }
        public int? OrderBy { get; set; }
        public int? Balance { get; set; }
        public int? DefaultValue { get; set; }
        public int? ParentID { get; set; }
        public int ProjectID { get; set; }
        public int EnableDelete { get; set; }
        public int enableupdate { get; set; }
    }
}
