// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetLeaveCountDetailResult
    {
        public int? EmployeeID { get; set; }
        public int? TypeID { get; set; }
        public int? AttendanceDate { get; set; }
        public int? amount { get; set; }
    }
}
