// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetProjectFeaturesResult
    {
        public string Description { get; set; }
        public int FeatureID { get; set; }
        public int? AllowedNumber { get; set; }
    }
}
