// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetProjectsResult
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string CompanyName { get; set; }
        public int? IsActive { get; set; }
        public string ReportPath { get; set; }
        public string imagepath { get; set; }
        public string footertitle1 { get; set; }
        public string footertitle2 { get; set; }
    }
}
