// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetScheduleTimeGroupResult
    {
        public int ScheduleTimeID { get; set; }
        public int GroupID { get; set; }
        public int ProjectID { get; set; }
        public int? createdby { get; set; }
        public DateTime? creationdate { get; set; }
        public int? modifiedby { get; set; }
        public DateTime? modificationDate { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
    }
}
