// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetScheduleTimeResult
    {
        public int ScheduleTimeID { get; set; }
        public int? DoorID { get; set; }
        public string Description { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public int? Suturday { get; set; }
        public int? Sunday { get; set; }
        public int? Monday { get; set; }
        public int? Tueseday { get; set; }
        public int? Whednesday { get; set; }
        public int? Thursday { get; set; }
        public int? friday { get; set; }
        public string EnableDesc { get; set; }
        public int? StatusID { get; set; }
    }
}
