// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetShiftDetailsResult
    {
        public int ShiftID { get; set; }
        public int DayID { get; set; }
        public int? StartTime { get; set; }
        public int? EndTime { get; set; }
        public int? IsWorkingDay { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public int? IsCalculated { get; set; }
        public int ProjectID { get; set; }
        public int BreakDay { get; set; }
        public int BreakEndTime { get; set; }
        public int BreakStartTime { get; set; }
        public int RamadanDay { get; set; }
        public int RamadanEndTime { get; set; }
        public int RamadanStartTime { get; set; }
        public int RamadanEndTimeRest { get; set; }
        public int RamadanStartTimeRest { get; set; }
    }
}
