// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetShiftsResult
    {
        public int ShiftID { get; set; }
        public string ShiftName { get; set; }
        public int? AllowedLate { get; set; }
        public int? CheckOutAfterMidNight { get; set; }
        public int? MorningAttendanceasAdditional { get; set; }
        public int? CalculateAdditionalIfExceed { get; set; }
        public int? FixedDayID { get; set; }
        public int? ShiftDays { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public int ProjectID { get; set; }
        public int EnableDelete { get; set; }
        public int Overtime { get; set; }
        public int? EarlyLeave { get; set; }
        public int? AllowedAdditionalBefore { get; set; }
        public int? ShouldCheckIn { get; set; }
        public int AllowedLatetooverride { get; set; }
        public int CheckoutShouldbeBefore { get; set; }
        public decimal AdditionalInWork { get; set; }
        public decimal AdditionalInHoliday { get; set; }
        public int IsActiveBreak { get; set; }
        public int BreakTypeID { get; set; }
        public int BreakPeriod { get; set; }
        public int IsBreakWillBeAddedToEndtime { get; set; }
        public int IsDynamicShift { get; set; }
        public int ShiftDailyWorkInMinutes { get; set; }
        public int ShiftNoOfDaysBerMonth { get; set; }
        public int ShiftAllowedMonthlyVacation { get; set; }
        public int WorkingPeriod { get; set; }
        public int ShouldCheckOut { get; set; }
        public decimal StaticOvertime { get; set; }
        public decimal HourRate { get; set; }
        public int? StartDate { get; set; }
        public int? EndDate { get; set; }
        public int ActivateRamadan { get; set; }
        public int? RamadanStartDate { get; set; }
        public int? RamadanEndDate { get; set; }
    }
}
