// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class GetShiftAllowanceResult
    {
        public int ProjectID { get; set; }
        public int ShiftID { get; set; }
        public int AllowanceID { get; set; }
        public int StartDate { get; set; }
        public int? EndDate { get; set; }
        public int? StatusID { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public string ShiftName { get; set; }
        public string AllowanceName { get; set; }
        public int AllowanceShiftID { get; set; }
    }
}
