// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("Holiday")]
    [Index("HolidayTypeID", Name = "IX_HolidayeType11")]
    [Index("FromDate", "ToDate", "ProjectID", Name = "NonClusteredIndex-20220712-031731")]
    [Index("ProjectID", Name = "ix_Holiday_111")]
    public partial class Holiday
    {
        [Key]
        public int HolidayID { get; set; }
        public int? HolidayTypeID { get; set; }
        public int? FromDate { get; set; }
        public int? ToDate { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string Notes { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        [Key]
        public int ProjectID { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("Holidays")]
        public virtual Project Project { get; set; }
    }
}