// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    public partial class Id
    {
        [Key]
        [Column("ID")]
        public int ID1 { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string NameID { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string TypeID { get; set; }
        [Key]
        public int ProjectID { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("Ids")]
        public virtual Project Project { get; set; }
    }
}