// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("LookupTable")]
    [Index("ID", Name = "ix_LoockupTable", IsUnique = true)]
    public partial class LookupTable
    {
        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string TableName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ColumnName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ColumnValue { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ColumnDescription { get; set; }
        public int? OrderBy { get; set; }
        public int? Balance { get; set; }
        public int? DefaultValue { get; set; }
        public int? ParentID { get; set; }
        [Key]
        public int ProjectID { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string ColumnDescriptionAr { get; set; }
        public int? EmployeeID { get; set; }
        public int? CalWithHoliday { get; set; }
        public int? IsInjuryVacation { get; set; }
        public int? IsHealthVacation { get; set; }
        public int? ApprovalProcessID { get; set; }
        public int? FirstPenaltyPeriod { get; set; }
        public int? SecondPenaltyPeriod { get; set; }
        public int? ThirdPenaltyPeriod { get; set; }
        public int? FourthPenaltyPeriod { get; set; }
        public int? FifthPenaltyPeriod { get; set; }
        public int? FirstPenaltyCategoryID { get; set; }
        public int? SecondPenaltyCategoryID { get; set; }
        public int? ThirdPenaltyCategoryID { get; set; }
        public int? FourthPenaltyCategoryID { get; set; }
        public int? FifthPenaltyCategoryID { get; set; }
        public int? IsPersonalVacation { get; set; }
        public int? IsWithoutSalaryVacation { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? WithoutSalaryVacationValue { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("LookupTables")]
        public virtual Project Project { get; set; }
    }
}