// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    public partial class Month
    {
        [Key]
        public int ID { get; set; }
        public int? MonthID { get; set; }
        public int? YearID { get; set; }
        [Key]
        public int ProjectID { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("Months")]
        public virtual Project Project { get; set; }
    }
}