// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("NotifciationSetupDetail")]
    public partial class NotifciationSetupDetail
    {
        [Key]
        public int NotifciationSetupID { get; set; }
        [Key]
        public int LevelID { get; set; }
        public int? FromApprovalProcessID { get; set; }
        public int? ToApprovalProcessID { get; set; }
        public int? AllowEdit { get; set; }
        public int? AllowDelete { get; set; }
    }
}