// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("NotifciationSetup")]
    public partial class NotifciationSetup
    {
        [Key]
        public int NotifciationSetupID { get; set; }
        public int? TypeID { get; set; }
        public int? RequestedBy { get; set; }
        public int? ProjectID { get; set; }
    }
}