// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class Online_GetprojectsResult
    {
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public byte[] ProjectLogo { get; set; }
        public int? Statusid { get; set; }
        public string TypeDesc { get; set; }
        public string validatetype { get; set; }
        public string validateid { get; set; }
        public DateTime? validateperidFrom { get; set; }
        public DateTime? validateperiodto { get; set; }
        public string Createdby { get; set; }
        public DateTime? creationdate { get; set; }
        public string acceptedby { get; set; }
        public DateTime? accepteddate { get; set; }
        public string footertitle1 { get; set; }
        public int? DependOnCheckType { get; set; }
    }
}
