// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    public partial class ProjectNotification
    {
        [Key]
        public int ProjectID { get; set; }
        [Key]
        public int NotificationID { get; set; }
        public int? StartPeriod { get; set; }
        public int? EndPeriod { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Creationdate { get; set; }
    }
}