// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    public partial class Reminder
    {
        [Key]
        public int ID { get; set; }
        public int? EmployeeID { get; set; }
        public int? PK { get; set; }
        public int? TypeID { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string Notes { get; set; }
        public int? EndDate { get; set; }
        public int? CreatedBy { get; set; }
        public int? ProjectID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string Description { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string DescriptionAr { get; set; }
        public int? UserID { get; set; }
        public int? IsDismissed { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
    }
}