// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models
{
    public partial class ResolveStringWithRowNumResult
    {
        public string Tstr { get; set; }
        public int TstrID { get; set; }
    }
}
