// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("ScheduleTimeDetail")]
    public partial class ScheduleTimeDetail
    {
        [Key]
        public int ScheduleTimeID { get; set; }
        [Key]
        public int DayID { get; set; }
        [Key]
        public int DetailID { get; set; }
        public int? FromTime { get; set; }
        public int? totime { get; set; }
        public int? StatusID { get; set; }

        [ForeignKey("ScheduleTimeID")]
        [InverseProperty("ScheduleTimeDetails")]
        public virtual ScheduleTime ScheduleTime { get; set; }
    }
}