// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("ScheduleTime")]
    public partial class ScheduleTime
    {
        public ScheduleTime()
        {
            ScheduleTimeDetails = new HashSet<ScheduleTimeDetail>();
        }

        [Key]
        public int ScheduleTimeID { get; set; }
        public int? DoorID { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string Description { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int? Suturday { get; set; }
        public int? Sunday { get; set; }
        public int? Monday { get; set; }
        public int? Tueseday { get; set; }
        public int? Whednesday { get; set; }
        public int? Thursday { get; set; }
        public int? friday { get; set; }
        public int? ProjectID { get; set; }
        public int? StatusID { get; set; }

        [InverseProperty("ScheduleTime")]
        public virtual ICollection<ScheduleTimeDetail> ScheduleTimeDetails { get; set; }
    }
}