// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    public partial class SettingDetail
    {
        [Key]
        public int SettingID { get; set; }
        [Key]
        public int DayID { get; set; }
        public int? StartTime { get; set; }
        public int? EndTime { get; set; }
        public int? IsWorkingDay { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        [Key]
        public int ProjectID { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("SettingDetails")]
        public virtual Project Project { get; set; }
    }
}