// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("ShiftAllowance")]
    public partial class ShiftAllowance
    {
        public int ProjectID { get; set; }
        public int ShiftID { get; set; }
        public int AllowanceID { get; set; }
        public int StartDate { get; set; }
        public int? EndDate { get; set; }
        public int? StatusID { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        [Key]
        public int AllowanceShiftID { get; set; }

        [ForeignKey("AllowanceID,ProjectID")]
        [InverseProperty("ShiftAllowances")]
        public virtual Allowance_deduction Allowance_deduction { get; set; }
    }
}