// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    public partial class Shift
    {
        public Shift()
        {
            EmployeeShiftDetails = new HashSet<EmployeeShiftDetail>();
        }

        [Key]
        public int ShiftID { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string ShiftName { get; set; }
        public int? AllowedLate { get; set; }
        public int? CheckOutAfterMidNight { get; set; }
        public int? MorningAttendanceasAdditional { get; set; }
        public int? CalculateAdditionalIfExceed { get; set; }
        public int? FixedDayID { get; set; }
        public int? ShiftDays { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int ProjectID { get; set; }
        public int? Overtime { get; set; }
        public int? StatusID { get; set; }
        public int? EarlyLeave { get; set; }
        public int? AllowedAdditionalBefore { get; set; }
        public int? ShouldCheckIn { get; set; }
        public int? AllowedLatetooverride { get; set; }
        public int? CheckoutShouldbeBefore { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? AdditionalInHoliday { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? AdditionalInWork { get; set; }
        public int? IsActiveBreak { get; set; }
        public int? BreakTypeID { get; set; }
        public int? BreakPeriod { get; set; }
        public int? IsBreakWillBeAddedToEndtime { get; set; }
        public int? IsDynamicShift { get; set; }
        public int? MaxOverTimePerDay { get; set; }
        public int? ShiftDailyWorkInMinutes { get; set; }
        public int? ShiftNoOfDaysBerMonth { get; set; }
        public int? ShiftAllowedMonthlyVacation { get; set; }
        public int? WorkingPeriod { get; set; }
        public int? ShouldCheckOut { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? StaticOvertime { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? HourRate { get; set; }
        public int? StartDate { get; set; }
        public int? EndDate { get; set; }
        public int? RamadanEndDate { get; set; }
        public int? RamadanStartDate { get; set; }
        public int? RamadanActivate { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("Shifts")]
        public virtual Project Project { get; set; }
        [InverseProperty("Shift")]
        public virtual ICollection<EmployeeShiftDetail> EmployeeShiftDetails { get; set; }
    }
}