// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    public partial class ShiftDetail
    {
        [Key]
        public int ShiftID { get; set; }
        [Key]
        public int DayID { get; set; }
        public int? StartTime { get; set; }
        public int? EndTime { get; set; }
        public int? IsWorkingDay { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModificationDate { get; set; }
        public int? IsCalculated { get; set; }
        [Key]
        public int ProjectID { get; set; }
        public int? BreakStartTime { get; set; }
        public int? BreakEndTime { get; set; }
        public int? BreakDay { get; set; }
        public int? RamadanDay { get; set; }
        public int? RamadanStartTime { get; set; }
        public int? RamadanEndTime { get; set; }
        public int? RamadanStartTimeRest { get; set; }
        public int? RamadanEndTimeRest { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("ShiftDetails")]
        public virtual Project Project { get; set; }
    }
}