// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("Tax")]
    public partial class Tax
    {
        [Key]
        public int TaxID { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Amount1 { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Amount2 { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? PercentAmount { get; set; }
    }
}