// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Table("Time")]
    public partial class Time
    {
        [Key]
        public int TimeID { get; set; }
        public int? TimeTypeID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Description { get; set; }
        public int? Orderedby { get; set; }
        [Key]
        public int ProjectID { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("Times")]
        public virtual Project Project { get; set; }
    }
}