// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    public partial class TransactionType
    {
        [Key]
        public int TransactionTypeID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string TransactionTypeDesc { get; set; }
        public int? IsPlus { get; set; }
        [Key]
        public int ProjectID { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("TransactionTypes")]
        public virtual Project Project { get; set; }
    }
}