// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Keyless]
    public partial class UserTypeButton
    {
        [StringLength(50)]
        [Unicode(false)]
        public string UserID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CanView { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CanAdd { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CanEdit { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ButtonID { get; set; }
    }
}