// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models
{
    [Index("UserTypeID", Name = "ix_Users")]
    [Index("UserTypeID", Name = "ix_Users123")]
    public partial class User
    {
        [Key]
        public int UserID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string UserName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string UserPassword { get; set; }
        [Key]
        public int ProjectID { get; set; }
        public int? StatusID { get; set; }
        public int? UserTypeID { get; set; }

        [ForeignKey("ProjectID")]
        [InverseProperty("Users")]
        public virtual Project Project { get; set; }
    }
}